### ISSUE TITLE
CI job fails intermittently

### ISSUE THREAD

**Issue by limed** [mdn/developer-portal#389]
During some builds the migrate task will fail because of the database not being up and ready yet and would fail with this error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  the database system is starting up
```

@escattone suggested we use `urlwait` https://pypi.org/project/urlwait/ for this to wait and proceed only when the db becomes ready. Subsequent builds after this fail will also throw errors like the following

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.27.0.4) and accepting
	TCP/IP connections on port 5432?
```

My suspicion here is that during the tear down process we never cleaned up the `.env` file properly which houses all the temporary passwords and also docker-compose is not tearing down the instance properly here. We can fix this my using `cleanWS()` in jenkins and running `docker-compose down --volumes --remove-orphans` before the build even happens

**Comment by escattone** [comment]
Just to add to what @limed has above, see https://github.com/mozilla/kuma/blob/6c99355a6623474bca20abd7c18f4f22a47cdeaf/Jenkinsfiles/utils.groovy#L238 for how MDN uses `urlwait`, and also how it wraps the test code with pre and post `docker-compose down --volumes --remove-orphans` commands.
